"""Auto-generated by train_flux_map_comparison.py.
Loads the best-performing model from out/models/ and exposes
predict(Id, Iq) -> (Phi_d, Phi_q) for downstream motor-control code.
Also exposes predict_batch(X) for fast MTPA/FW sweeps (X: (n,2)).
Regenerate this file by re-running the training script (or keep
predict_batch when manually pointing at a pkl winner).
"""
import os
import pickle

import numpy as np

_ARTIFACT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                         "out", "models", "random_forest.pkl")
with open(_ARTIFACT, "rb") as _f:
    _obj = pickle.load(_f)
_MODEL = _obj["model"]
_SCALER = _obj.get("scaler")


def predict_batch(X):
    """X: array-like (n, 2) of [Id, Iq]. Returns (n, 2) Phi_d, Phi_q."""
    X = np.asarray(X, dtype=np.float64)
    if X.ndim == 1:
        X = X.reshape(1, -1)
    if _SCALER is not None:
        Xs = _SCALER.transform(X)
    else:
        Xs = X
    Y = np.asarray(_MODEL.predict(Xs), dtype=np.float64)
    if Y.ndim == 1:
        Y = Y.reshape(-1, 2)
    return Y


def predict(Id, Iq):
    Y = predict_batch([[Id, Iq]])
    return float(Y[0, 0]), float(Y[0, 1])


_ARTIFACT_PATH = _ARTIFACT
