"""Auto-generated by train_flux_map_comparison.py / promote_inference_model.
Loads a selected model from out/models/ and exposes
predict(Id, Iq) -> (Phi_d, Phi_q) for downstream motor-control code.
Also exposes predict_batch(X) for fast MTPA/FW sweeps when available.
Regenerate by re-running training or run_offline_pipeline.py.
"""

import os, numpy as np
try:
    import torch
    from torch import nn
except ImportError as _e:
    raise ImportError("inference_flux_map.py needs torch for model 'mlp_small'") from _e

_ARTIFACT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                         "out", "models", "mlp_small.pt")
_chk = torch.load(_ARTIFACT, map_location="cpu", weights_only=False)
_ARCH = _chk["arch"]
_X_MU = _chk["x_mu"]; _X_SIGMA = _chk["x_sigma"]
_Y_MU = _chk["y_mu"]; _Y_SIGMA = _chk["y_sigma"]

class _MLPSmall(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(2, 32), nn.ReLU(),
                                 nn.Linear(32, 32), nn.ReLU(),
                                 nn.Linear(32, 2))
    def forward(self, x): return self.net(x)

class _MLPMedium(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(2, 64), nn.ReLU(), nn.Dropout(0.1),
                                 nn.Linear(64, 64), nn.ReLU(), nn.Dropout(0.1),
                                 nn.Linear(64, 2))
    def forward(self, x): return self.net(x)

class _MLPLarge(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(2, 128), nn.ReLU(), nn.Dropout(0.2),
                                 nn.Linear(128, 128), nn.ReLU(), nn.Dropout(0.2),
                                 nn.Linear(128, 64), nn.ReLU(), nn.Dropout(0.1),
                                 nn.Linear(64, 2))
    def forward(self, x): return self.net(x)

class _MLPPhys(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(5, 64), nn.ReLU(), nn.Dropout(0.1),
                                 nn.Linear(64, 64), nn.ReLU(), nn.Dropout(0.1),
                                 nn.Linear(64, 2))
    def forward(self, x): return self.net(x)

class _MLPPhysAdapter(nn.Module):
    def __init__(self, x_mu, x_sigma):
        super().__init__()
        self.x_mu = nn.Parameter(torch.tensor(x_mu).float(), requires_grad=False)
        self.x_sigma = nn.Parameter(torch.tensor(x_sigma).float(), requires_grad=False)
        self.net = _MLPPhys()
    def forward(self, x):
        xs = (x - self.x_mu) / self.x_sigma
        aug = torch.cat([xs, (xs[:,0:1] * xs[:,1:2]),
                         (xs[:,0:1]**2), (xs[:,1:2]**2)], dim=1)
        return self.net.net(aug)

_NET_CLS = {'_MLPSmall': _MLPSmall, '_MLPMedium': _MLPMedium,
            '_MLPLarge': _MLPLarge,
            '_MLPPhysAdapter': _MLPPhysAdapter}.get(_ARCH, _MLPMedium)
_NET = _NET_CLS()
if _ARCH == '_MLPPhysAdapter':
    _NET = _MLPPhysAdapter(np.zeros(2), np.ones(2))
_NET.load_state_dict(_chk["state_dict"])
_NET.eval()

def predict_batch(X):
    X = np.asarray(X, dtype=np.float64)
    if X.ndim == 1:
        X = X.reshape(1, -1)
    Xs = (X - _X_MU) / _X_SIGMA
    with torch.no_grad():
        Ys = _NET(torch.from_numpy(Xs).float()).numpy()
    return Ys * _Y_SIGMA + _Y_MU
def predict(Id, Iq):
    Y = predict_batch([[Id, Iq]])
    return float(Y[0, 0]), float(Y[0, 1])
_ARTIFACT_PATH = _ARTIFACT
