"""MTPA + field-weakening reference lookup from the validated flux surrogate.

Reads:
    inference_flux_map.py   (auto-generated by train_flux_map_comparison.py)
        -> exposes predict(Id, Iq) -> (Phi_d, Phi_q)
    (optional) motor_params.json          (written by pull_motor_params.py
                                           running in AEDT; if absent, falls
                                           back to CLI args / defaults)

Computes operating-envelope characterization for an IPM motor:
  T(Id, Iq) = (3/2) * P * (Phi_d(Id,Iq) * Iq - Phi_q(Id,Iq) * Id)

Outputs (under out/mtpa/):
  - motor_params_used.json              - the parameters actually used
  - mtpa_curve.csv                      - (T_ref, Id_mtpa, Iq_mtpa, |I_s|)
  - fw_envelope.csv                     - (rpm, T_max_fw, Id_fw, Iq_fw, |I_s|, |V|)
  - reference_lookup.csv                - dense (rpm, T_ref) -> (Id_ref, Iq_ref)
                                          grid for the controller's LUT
  - mtpa_fw_overview.png                - 4-panel plot:
                                          (1) flux map Phi_d(Id, Iq)
                                          (2) T(Id, Iq) isotorque contours
                                              + MTPA curve overlay
                                          (3) T-rpm envelope with limited
                                              current and voltage circles
                                          (4) Id_ref/Iq_ref reference LUT
  - torque_sanity.log                   - rated point check (implied rated
                                          torque from surrogate vs. expected)

The script prints a rated-torque sanity check at startup. If the implied
rated torque is off from the expected value (default 2.89531 N.m, taken
from RMxprt 0.res), it prints the flux scale factor that would fix it;
re-run with --flux-scale <that_value>.

CLI args:
  --poles               default 4 (number of poles; pole pairs = poles/2)
  --rs                  default 2.15938 (per-phase stator resistance, ohm)
  --vdc                 default 311  (DC bus voltage, V; sqrt(2)*220)
  --omega-mech-max-rpm  default 6000  (max mechanical speed, rpm)
  --omega-mech-base-rpm default 1800  (base / synchronous speed, rpm)
  --i-max-peak          default 6.0  (peak stator current amplitude, A)
  --t-ref-max           default 4.0  (upper torque sweep bound, N.m)
  --n-t-ref             default 50  (MTPA Torque samples)
  --n-rpm               default 60  (FW speed samples)
  --flux-scale          default 1.0  (multiplier to convert FEM flux linkage
                                     to SI Wb-turns; see torque sanity)
  --models-dir          default out
  --out                 default out/mtpa
  --params-json         optional path to motor_params.json (from pull_motor_params.py);
                        if present, overrides the CLI defaults with values
                        found there; CLI args still take priority via
                        --no-use-params-json


Usage:
    .venv\\Scripts\\python mtpa_field_weakening.py \\
        --params-json out/motor_params.json
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import warnings

import numpy as np

warnings.filterwarnings("ignore")

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    _HAS_MPL = True
except ImportError:
    _HAS_MPL = False


# ---------------------------------------------------------------------------
# Surrogate loading. The auto-generated inference_flux_map.py exposes
# predict(Id, Iq) -> (Phi_d, Phi_q). We wrap it as a vectorized fn for the
# dense sweeps in this script.
# ---------------------------------------------------------------------------

def _load_surrogate():
    """Import the auto-generated inference module next to this script."""
    here = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, here)
    try:
        import inference_flux_map as inf
    except ImportError as exc:
        raise FileNotFoundError(
            "inference_flux_map.py not found at " + here + ". Run "
            "train_flux_map_comparison.py first - it auto-generates that "
            "file next to itself once a winning model is picked."
        ) from exc
    if not hasattr(inf, "predict"):
        raise RuntimeError(
            "inference_flux_map.py does not expose predict(Id, Iq). "
            "Regenerate it by re-running train_flux_map_comparison.py."
        )
    return inf, os.path.join(here, "inference_flux_map.py")


# ---------------------------------------------------------------------------
# Units + transforms.
# ---------------------------------------------------------------------------

def rpm_to_elec(rad_per_s_elec, n_pole_pairs):
    """Convert mechanical rpm to electrical rad/s."""
    # omega_mech (rad/s) = rpm * 2*pi / 60
    # omega_elec (rad/s) = omega_mech * pole_pairs
    return None  # placeholder if needed


def rpm_mech_to_we(rpm_mech, n_pp):
    return (rpm_mech / 60.0) * 2.0 * math.pi * n_pp  # rad/s electrical


# ---------------------------------------------------------------------------
# Surrogate wrappers.
# ---------------------------------------------------------------------------

class FluxSurrogate:
    def __init__(self, inf_module, flux_scale=1.0):
        self._predict = inf_module.predict
        # Prefer batched path (sklearn RF / numpy models); fall back to scalar loop.
        self._predict_batch = getattr(inf_module, "predict_batch", None)
        self.flux_scale = float(flux_scale)

    def predict(self, X):
        """X: (n, 2) array of [Id, Iq].  Returns (n, 2) array of [Phi_d, Phi_q]."""
        X = np.asarray(X, dtype=np.float64)
        if X.ndim == 1:
            X = X.reshape(1, -1)
        n = X.shape[0]
        if self._predict_batch is not None:
            Y = np.asarray(self._predict_batch(X), dtype=np.float64)
            if Y.ndim == 1:
                Y = Y.reshape(-1, 2)
            return Y * self.flux_scale
        # Scalar fallback (slow): one model call per row.
        out = np.empty((n, 2), dtype=np.float64)
        for i in range(n):
            pd, pq = self._predict(float(X[i, 0]), float(X[i, 1]))
            out[i, 0] = pd * self.flux_scale
            out[i, 1] = pq * self.flux_scale
        return out

    def torque(self, X, n_pp):
        """IPM torque for each row of X.

        T = (3/2) * P * (Phi_d * Iq - Phi_q * Id)
        """
        Y = self.predict(X)
        T = 1.5 * n_pp * (Y[:, 0] * X[:, 1] - Y[:, 1] * X[:, 0])
        return T, Y

    def voltage(self, X, omega_e, R_s, Y=None):
        """Stator dq-frame voltage magnitudes.
        V_d = R_s * Id - omega_e * Phi_q
        V_q = R_s * Iq + omega_e * Phi_d
        (motor convention, omega_e = electrical angular vel rad/s)

        Optional Y: precomputed flux (n,2) to avoid a second model call.
        """
        if Y is None:
            Y = self.predict(X)
        Vd = R_s * X[:, 0] - omega_e * Y[:, 1]
        Vq = R_s * X[:, 1] + omega_e * Y[:, 0]
        return np.sqrt(Vd * Vd + Vq * Vq), Vd, Vq


# ---------------------------------------------------------------------------
# MTPA solver + FW envelope sweep.
# ---------------------------------------------------------------------------

def mtpa_for_torque(T_ref, surrogate, n_pp, i_max, grid_n=400,
                    n_local=20):
    """For a given target torque T_ref, find (Id, Iq) that uses minimum
    stator current magnitude. Two-phase search:
      1. Dense uniform grid over |I_s| disk + torque constraint surface
      2. fine local refinement around best grid point

    Constraint: T(Id, Iq) = T_ref (== approx) AND |I_s| <= i_max.
    Objective: minimize |I_s| = sqrt(Id^2 + Iq^2).
    """
    # Search window. MTPA is conventionally in [-i_max, 0] for Id (FW side)
    # and [0, i_max] for Iq. Mirror for negative T_ref.
    sign = 1.0 if T_ref >= 0 else -1.0
    i_max_a = float(i_max)

    # Grid over the upper half-disk (Iq >= 0); flip sign at the end.
    id_grid = np.linspace(-i_max_a, 0.0, grid_n)
    iq_grid = np.linspace(0.0, i_max_a, grid_n)
    II, QQ = np.meshgrid(id_grid, iq_grid, indexing="ij")
    pts = np.stack([II.ravel(), QQ.ravel()], axis=1)
    T_arr, _ = surrogate.torque(pts, n_pp)
    diff = T_arr - T_ref
    mask = (np.abs(diff) < 0.05 * max(abs(T_ref), 1e-3)) & (np.sqrt(pts[:,0]**2 + pts[:,1]**2) <= i_max_a * 1.001)
    if not np.any(mask):
        # Looser tolerance
        mask = (np.abs(diff) < 0.20 * max(abs(T_ref), 1e-3)) & (np.sqrt(pts[:,0]**2 + pts[:,1]**2) <= i_max_a * 1.001)
    if not np.any(mask):
        return None
    cand = pts[mask]
    Is = np.sqrt(cand[:,0]**2 + cand[:,1]**2)
    best = int(np.argmin(Is))
    x_best = cand[best].copy()
    # Local search around x_best (coordinate-descent-style).
    step = 0.02 * i_max_a
    T_tol = 0.005 * max(abs(T_ref), 1e-3)
    for _ in range(n_local):
        for dim in (0, 1):
            for d in (+step, -step):
                cand_x = x_best.copy()
                cand_x[dim] += d
                if math.hypot(cand_x[0], cand_x[1]) > i_max_a * 1.0001:
                    continue
                T_j, _ = surrogate.torque(cand_x[None, :], n_pp)
                if abs(T_j[0] - T_ref) < T_tol or abs(T_j[0] - T_ref) < abs(surrogate.torque(x_best[None, :], n_pp)[0][0] - T_ref):
                    cand_j_norm = math.hypot(cand_x[0], cand_x[1])
                    best_norm = math.hypot(x_best[0], x_best[1])
                    if cand_j_norm < best_norm + 1e-9:
                        x_best = cand_x
        step *= 0.8
    return float(x_best[0]) * sign, float(x_best[1]) * sign, float(math.hypot(x_best[0], x_best[1]))


def mtpa_curve(surrogate, n_pp, i_max, t_refs, grid_n=400):
    """Returns list of (T_ref, Id, Iq, |I_s|)."""
    out = []
    for t in t_refs:
        r = mtpa_for_torque(t, surrogate, n_pp, i_max, grid_n=grid_n)
        if r is None:
            out.append((t, float("nan"), float("nan"), float("nan")))
        else:
            out.append((t, r[0], r[1], r[2]))
    return out


def fw_envelope(surrogate, n_pp, R_s, V_max, i_max, rpms):
    """For each mechanical speed (rpm), find the maximum torque subject to
    BOTH the current limit |Is| <= i_max AND the voltage limit |V| <= V_max.

    Strategy: brute force candidate generation over a fine grid in the dq
    plane, filter by both constraints, take the max achievable |T|.
    """
    out = []
    i_max_a = float(i_max)
    id_grid = np.linspace(-i_max_a, 0.0, 160)
    iq_grid = np.linspace(0.0, i_max_a, 160)
    II, QQ = np.meshgrid(id_grid, iq_grid, indexing="ij")
    pts = np.stack([II.ravel(), QQ.ravel()], axis=1)
    Is_all = np.sqrt(pts[:, 0] ** 2 + pts[:, 1] ** 2)
    cur_mask = Is_all <= i_max_a * 1.001
    # One batched flux eval for the whole dq grid (reused for T and all V(rpm)).
    T_all, Y_all = surrogate.torque(pts, n_pp)
    for rpm in rpms:
        omega_e = rpm_mech_to_we(float(rpm), n_pp)
        V_all, _, _ = surrogate.voltage(pts, omega_e, R_s, Y=Y_all)
        mask = cur_mask & (V_all <= V_max * 1.001)
        if not np.any(mask):
            out.append((float(rpm), float("nan"), float("nan"),
                        float("nan"), float("nan"), float("nan")))
            continue
        # Take the candidate with largest |T| at positive torque (motoring).
        idx = int(np.argmax(T_all[mask]))
        sel_pts = pts[mask]
        sel_T = T_all[mask]
        sel_V = V_all[mask]
        sel_Is = Is_all[mask]
        chosen = sel_pts[idx]
        out.append((float(rpm), float(sel_T[idx]), float(chosen[0]),
                    float(chosen[1]), float(sel_Is[idx]), float(sel_V[idx])))
    return out


def reference_lookup(surrogate, n_pp, R_s, V_max, i_max,
                     t_refs, rpms, grid_n=400, mtpa=None, env=None):
    """For each (rpm, T_ref), solve for min-|Is| feasible (Id, Iq).

    Same Id/Iq resolution as MTPA (default grid_n=400 half-disk), but one
    batched flux eval per rpm instead of nested micro-batches (which thrash
    sklearn RandomForest call overhead).

    If T_ref exceeds the FW envelope max at that rpm, mark infeasible and
    write the envelope-limited operating point instead.
    """
    if env is None:
        env = fw_envelope(surrogate, n_pp, R_s, V_max, i_max, rpms)
    if mtpa is None:
        mtpa = mtpa_curve(surrogate, n_pp, i_max, t_refs, grid_n=grid_n)
    env_dict = {row[0]: row for row in env}
    mtpa_dict = {row[0]: (row[1], row[2], row[3]) for row in mtpa}

    i_max_a = float(i_max)
    id_grid = np.linspace(-i_max_a, 0.0, grid_n)
    iq_grid = np.linspace(0.0, i_max_a, grid_n)
    II, QQ = np.meshgrid(id_grid, iq_grid, indexing="ij")
    pts = np.stack([II.ravel(), QQ.ravel()], axis=1)
    Is_all = np.sqrt(pts[:, 0] ** 2 + pts[:, 1] ** 2)
    cur_mask = Is_all <= i_max_a * 1.001

    # Flux/torque independent of speed — evaluate once for the whole grid.
    T_all, Y_all = surrogate.torque(pts, n_pp)

    rows = []
    for rpm in rpms:
        omega_e = rpm_mech_to_we(float(rpm), n_pp)
        V_all, _, _ = surrogate.voltage(pts, omega_e, R_s, Y=Y_all)
        volt_mask = V_all <= V_max * 1.001
        env_row = env_dict[rpm]
        T_max_fw = env_row[1] if not math.isnan(env_row[1]) else 0.0
        env_id, env_iq = env_row[2], env_row[3]

        for t in t_refs:
            if math.isnan(T_max_fw) or t > T_max_fw + 1e-6:
                rows.append((float(rpm), float(t), env_id, env_iq,
                             float("nan"), "infeasible"))
                continue
            mtpa_id, mtpa_iq, mtpa_norm = mtpa_dict[t]
            if math.isnan(mtpa_id):
                rows.append((float(rpm), float(t), float("nan"), float("nan"),
                             float("nan"), "mtpa_unavailable"))
                continue
            # MTPA point voltage check (single-row batch).
            X_try = np.array([[mtpa_id, mtpa_iq]])
            V_try, _, _ = surrogate.voltage(X_try, omega_e, R_s)
            if V_try[0] <= V_max * 1.001:
                rows.append((float(rpm), float(t), float(mtpa_id),
                             float(mtpa_iq), float(mtpa_norm), "mtpa"))
                continue
            # Voltage-limited: min |Is| on full-resolution grid with
            # |T - T_ref| tolerance and |V|<=V_max (same half-disk as MTPA).
            T_tol = 0.05 * max(abs(t), 1e-3)
            mask = (
                cur_mask & volt_mask
                & (np.abs(T_all - t) < T_tol)
            )
            if not np.any(mask):
                T_tol = 0.20 * max(abs(t), 1e-3)
                mask = (
                    cur_mask & volt_mask
                    & (np.abs(T_all - t) < T_tol)
                )
            if not np.any(mask):
                rows.append((float(rpm), float(t), float("nan"), float("nan"),
                             float("nan"), "fw_search_failed"))
                continue
            sub = np.where(mask)[0]
            k = sub[int(np.argmin(Is_all[sub]))]
            rows.append((
                float(rpm), float(t),
                float(pts[k, 0]), float(pts[k, 1]),
                float(Is_all[k]), "fw",
            ))
    return rows, env


# ---------------------------------------------------------------------------
# Sanity check.
# ---------------------------------------------------------------------------

def torque_sanity(surrogate, n_pp, i_rated_peak, t_rated, out_dir):
    """At (Id, Iq) = (0, I_rated_peak) the implied torque should be in the
    right neighborhood of T_rated. If wildly off, print a suggested
    --flux-scale to fix it. (0, Iq) is the pure-PM-torque operating point;
    real MTPA for IPMs uses Id < 0, but (0, rated) is a stable enough probe
    to detect a flux units mismatch."""
    X = np.array([[0.0, float(i_rated_peak)]])
    T_pred, Y_pred = surrogate.torque(X, n_pp)
    T_pred_val = float(T_pred[0])
    scale_factor = t_rated / T_pred_val if abs(T_pred_val) > 1e-9 else float("nan")
    lines = []
    lines.append("Torque sanity check")
    lines.append("  Point explored: Id=0, Iq=I_rated_peak=%.4f A" % i_rated_peak)
    lines.append("  Surrogate Phi_d=%.6e Wb, Phi_q=%.6e Wb" % (Y_pred[0, 0], Y_pred[0, 1]))
    lines.append("  Implied rated torque T = %.6e N.m" % T_pred_val)
    lines.append("  Expected rated torque T = %.6e N.m (from RMxprt 0.res)" % t_rated)
    if math.isfinite(scale_factor) and (scale_factor < 0.1 or scale_factor > 10.0):
        lines.append("  >>> OFF by factor %.3f - flux linkage units mismatch. Suggested re-run:" % scale_factor)
        lines.append("  >>> python mtpa_field_weakening.py --flux-scale %.6g"
                     % scale_factor)
    elif abs(scale_factor - 1.0) < 0.05:
        lines.append("  OK - implied torque within 5% of rated.")
    else:
        lines.append("  WARNING: implied torque within %.1f%% of rated; check results carefully."
                     % (100.0 * abs(scale_factor - 1.0)))
    log = "\n".join(lines) + "\n"
    print(log)
    with open(os.path.join(out_dir, "torque_sanity.log"), "w") as f:
        f.write(log)


# ---------------------------------------------------------------------------
# Plots.
# ---------------------------------------------------------------------------

def plot_overview(surrogate, n_pp, i_max, mtpa, env, lookup, out_dir):
    if not _HAS_MPL:
        return
    fig, axes = plt.subplots(2, 2, figsize=(14, 11))

    # (0, 0) Phi_d(Id, Iq)
    id_grid = np.linspace(-i_max, 0, 80)
    iq_grid = np.linspace(0, i_max, 80)
    II, QQ = np.meshgrid(id_grid, iq_grid, indexing="ij")
    pts = np.stack([II.ravel(), QQ.ravel()], axis=1)
    Ph = surrogate.predict(pts)
    PD = Ph[:, 0].reshape(II.shape)
    PQ = Ph[:, 1].reshape(II.shape)
    ax = axes[0][0]
    cs = ax.contourf(II, QQ, PD, levels=24, cmap="viridis")
    fig.colorbar(cs, ax=ax, label="Phi_d (Wb)")
    ax.set_xlabel("Id (A)"); ax.set_ylabel("Iq (A)")
    ax.set_title("Surrogate Phi_d(Id, Iq)")

    # (0, 1) Torque map + MTPA curve
    T_arr, _ = surrogate.torque(pts, n_pp)
    T_map = T_arr.reshape(II.shape)
    ax = axes[0][1]
    cs = ax.contourf(II, QQ, T_map, levels=24, cmap="RdBu_r")
    ax.contour(II, QQ, T_map, levels=12, colors="k", linewidths=0.3)
    fig.colorbar(cs, ax=ax, label="T (N.m)")
    if mtpa:
        ids = [r[1] for r in mtpa if not math.isnan(r[1])]
        iqs = [r[2] for r in mtpa if not math.isnan(r[2])]
        ax.plot(ids, iqs, "o-", color="black", ms=3, label="MTPA")
        ax.legend(loc="upper right", fontsize=8)
    ax.set_xlabel("Id (A)"); ax.set_ylabel("Iq (A)")
    ax.set_title("Isotorque contours + MTPA")

    # (1, 0) T-rpm envelope
    ax = axes[1][0]
    rpms_arr = np.array([r[0] for r in env], dtype=np.float64)
    T_max_arr = np.array([r[1] for r in env], dtype=np.float64)
    ax.plot(rpms_arr, T_max_arr, "-", color="C0", label="T_max (FW envelope)")
    ax.set_xlabel("mech rpm"); ax.set_ylabel("T_max (N.m)")
    ax.set_title("Torque-speed envelope under I and V limits")
    ax.legend(fontsize=9)

    # (1, 1) Reference LUT (rows end with a status string — do not cast all cols)
    ax = axes[1][1]
    meas = []
    for row in lookup:
        try:
            id_ref = float(row[2])
            iq_ref = float(row[3])
        except (TypeError, ValueError):
            continue
        if math.isnan(id_ref) or math.isnan(iq_ref):
            continue
        if str(row[5]) in ("infeasible", "mtpa_unavailable", "fw_search_failed"):
            continue
        meas.append((float(row[0]), float(row[1]), id_ref, iq_ref))
    if len(meas) >= 3:
        arr = np.array(meas, dtype=np.float64)
        rpms_uniq = np.unique(arr[:, 0])
        for r in rpms_uniq[:: max(1, int(len(rpms_uniq) / 8))]:
            sel = arr[arr[:, 0] == r]
            ax.plot(sel[:, 1], sel[:, 3], "o-", ms=3,
                    label="%.0f rpm" % r)
    ax.set_xlabel("T_ref (N.m)"); ax.set_ylabel("Iq_ref (A)")
    ax.set_title("Reference LUT (Iq_ref vs T_ref at selected speeds)")
    ax.legend(fontsize=7, loc="best")

    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, "mtpa_fw_overview.png"), dpi=140)
    plt.close(fig)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--poles", type=int, default=4,
                   help="Number of poles (pole pairs = poles/2). Default 4")
    p.add_argument("--rs", type=float, default=2.15938,
                   help="Per-phase stator resistance (ohm). Default 2.15938 "
                        "(from RMxprt 0.res at 75C)")
    p.add_argument("--vdc", type=float, default=311,
                   help="DC bus voltage (V). Default 311 = sqrt(2)*220")
    p.add_argument("--omega-mech-max-rpm", type=float, default=6000.0,
                   help="Max mechanical speed (rpm) for FW sweep. Default 6000")
    p.add_argument("--omega-mech-base-rpm", type=float, default=1800.0,
                   help="Base / synchronous speed (rpm). Default 1800")
    p.add_argument("--i-max-peak", type=float, default=6.0,
                   help="Peak stator current amplitude (A) - |Is| limit. "
                        "Default 6.0 (RMxprt maximum current)")
    p.add_argument("--t-ref-max", type=float, default=4.0,
                   help="Upper torque sweep bound (N.m). Default 4.0 "
                        "(rated torque is 2.89531 N.m)")
    p.add_argument("--n-t-ref", type=int, default=50,
                   help="Number of torque samples for MTPA curve. Default 50")
    p.add_argument("--n-rpm", type=int, default=60,
                   help="Number of speed samples for FW envelope. Default 60")
    p.add_argument("--flux-scale", type=float, default=1.0,
                   help="Multiplier from FEM flux linkage to SI Wb-turns. "
                        "Default 1.0. See torque_sanity.log.")
    p.add_argument("--i-rated-peak", type=float, default=4.00807,
                   help="Rated current peak (A) for sanity check. Default 4.00807 "
                        "(= 2.83481 Arms * sqrt(2))")
    p.add_argument("--t-rated", type=float, default=2.89531,
                   help="Rated torque (N.m) for sanity check. Default 2.89531")
    p.add_argument("--models-dir", default="out",
                   help="Unused placeholder for compatibility.")
    p.add_argument("--out", default="out/mtpa",
                   help="Output dir. Default out/mtpa")
    p.add_argument("--params-json", default="data/motor_params.json",
                   help="Optional motor_params.json from pull_motor_params.py "
                        "(default: data/motor_params.json). If present and readable, "
                        "overrides CLI defaults for poles/rs/vdc/i-max/flux-scale/"
                        "t-rated/i-rated-peak using keys found there.")
    p.add_argument("--no-use-params-json", action="store_true",
                   help="Ignore --params-json even if it exists.")
    return p.parse_args()


def overlay_params_from_json(ns):
    if ns.no_use_params_json:
        return
    p = ns.params_json
    if not p or not os.path.exists(p):
        return
    try:
        with open(p, "r") as f:
            j = json.load(f)
    except Exception:
        return
    def copy_if(key, attr, cast):
        if key in j and j[key] is not None:
            try:
                setattr(ns, attr, cast(j[key]))
                print(f"[params-json] overriding {attr} = {j[key]}")
            except Exception:
                pass
    copy_if("poles", "poles", int)
    copy_if("pole_pairs", "poles", lambda v: int(v*2))  # tolerate pole_pairs
    copy_if("rs_ohm", "rs", float)
    copy_if("vdc_v", "vdc", float)
    copy_if("i_max_peak_a", "i_max_peak", float)
    copy_if("i_rated_peak_a", "i_rated_peak", float)
    copy_if("t_rated_nm", "t_rated", float)
    copy_if("flux_scale", "flux_scale", float)
    copy_if("flux_scale", "flux_scale", float)
    copy_if("omega_mech_base_rpm", "omega_mech_base_rpm", float)
    copy_if("omega_mech_max_rpm", "omega_mech_max_rpm", float)


def write_csv(path, header, rows, fmt_row=None):
    import csv
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        for r in rows:
            if fmt_row:
                w.writerow(fmt_row(r))
            else:
                w.writerow(r)


def main():
    ns = parse_args()
    overlay_params_from_json(ns)

    os.makedirs(ns.out, exist_ok=True)

    inf, inf_path = _load_surrogate()
    print(f"[load] inference module: {inf_path}")

    surrogate = FluxSurrogate(inf, flux_scale=ns.flux_scale)

    # V_max via SVPWM: max |V_dq| per phase (peak) = vdc / sqrt(3).
    V_max = ns.vdc / math.sqrt(3.0)
    # Account for inverter drop optionally absorbed in vdc; user adjusts if needed.
    print(f"[params] poles={ns.poles}, pp={ns.poles//2}, rs={ns.rs:.4f} ohm, "
          f"V_dc={ns.vdc:.1f} V -> V_max_phase_peak(SVPWM)={V_max:.3f} V")
    print(f"[params] i_max_peak={ns.i_max_peak} A, "
          f"omega_base={ns.omega_mech_base_rpm} rpm, "
          f"omega_max={ns.omega_mech_max_rpm} rpm, "
          f"flux_scale={ns.flux_scale:.4g}")

    torque_sanity(surrogate, ns.poles // 2, ns.i_rated_peak, ns.t_rated,
                  ns.out)

    # Save params.
    with open(os.path.join(ns.out, "motor_params_used.json"), "w") as f:
        json.dump({
            "poles": int(ns.poles),
            "pole_pairs": int(ns.poles // 2),
            "rs_ohm": ns.rs,
            "vdc_v": ns.vdc,
            "vmax_phase_peak_v": V_max,
            "i_max_peak_a": ns.i_max_peak,
            "i_rated_peak_a": ns.i_rated_peak,
            "t_rated_nm": ns.t_rated,
            "flux_scale": ns.flux_scale,
            "omega_mech_base_rpm": ns.omega_mech_base_rpm,
            "omega_mech_max_rpm": ns.omega_mech_max_rpm,
            "inference_path": inf_path,
        }, f, indent=2)

    # MTPA curve (400x400 Id-Iq half-disk per torque sample; batched RF).
    print("\n[mtpa] computing MTPA curve over %d torque samples (grid_n=400)..."
          % ns.n_t_ref)
    t_refs = np.linspace(0.0, ns.t_ref_max, ns.n_t_ref).tolist()
    mtpa = mtpa_curve(surrogate, ns.poles // 2, ns.i_max_peak, t_refs,
                      grid_n=400)
    write_csv(os.path.join(ns.out, "mtpa_curve.csv"),
              ["T_ref_Nm", "Id_A", "Iq_A", "Is_norm_A"],
              mtpa,
              fmt_row=lambda r: [("%.6f" % r[0]), ("%.6f" % r[1]),
                                  ("%.6f" % r[2]), ("%.6f" % r[3])])
    print(f"[mtpa] wrote {os.path.join(ns.out, 'mtpa_curve.csv')}")

    # FW envelope.
    print("\n[fw] computing torque-speed envelope over %d rpm samples..."
          % ns.n_rpm)
    rpms = np.linspace(0.0, ns.omega_mech_max_rpm, ns.n_rpm).tolist()
    env = fw_envelope(surrogate, ns.poles // 2, ns.rs, V_max,
                      ns.i_max_peak, rpms)
    write_csv(os.path.join(ns.out, "fw_envelope.csv"),
              ["rpm", "T_max_fw_Nm", "Id_A", "Iq_A", "Is_norm_A", "V_norm_V"],
              env,
              fmt_row=lambda r: [("%.6f" % r[0]), ("%.6f" % r[1]),
                                  ("%.6f" % r[2]), ("%.6f" % r[3]),
                                  ("%.6f" % r[4]), ("%.6f" % r[5])])
    print(f"[fw] wrote {os.path.join(ns.out, 'fw_envelope.csv')}")

    # Reference LUT — reuse mtpa/env; full-res 400x400 batch per rpm.
    print("\n[ref] computing full reference look-up (rpm x T_ref), "
          "grid_n=400 batched...")
    lookup, _ = reference_lookup(
        surrogate, ns.poles // 2, ns.rs, V_max,
        ns.i_max_peak, t_refs, rpms,
        grid_n=400, mtpa=mtpa, env=env,
    )
    write_csv(os.path.join(ns.out, "reference_lookup.csv"),
              ["rpm_mech", "T_ref_Nm", "Id_ref_A", "Iq_ref_A", "Is_norm_A", "status"],
              lookup,
              fmt_row=lambda r: [("%.6f" % r[0]), ("%.6f" % r[1]),
                                  ("%.6f" % r[2]), ("%.6f" % r[3]),
                                  ("%.6f" % r[4]), str(r[5])])
    print(f"[ref] wrote {os.path.join(ns.out, 'reference_lookup.csv')}")

    # Plot.
    plot_overview(surrogate, ns.poles // 2, ns.i_max_peak, mtpa, env, lookup,
                  ns.out)
    print(f"\n[done] outputs under {ns.out}")
    print("Next: feed reference_lookup.csv into the motor-controller LUT, OR "
          "run pull_motor_params.py (AEDT) to verify --flux-scale and "
          "poles/vdc before locking the LUT in.")


if __name__ == "__main__":
    main()